### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by almansi** [gopherjs/gopherjs#435]
When typing in go 1.5 and 1.6: go get -u github.com/gopherjs/gopherjs
I get:

```
# github.com/gopherjs/gopherjs/compiler
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:341: cannot use ty (type "go/types".Type) as type "golang.org/x/tools/go/types".Type in argument to c.p.anonTypeMap.At:
	"go/types".Type does not implement "golang.org/x/tools/go/types".Type (wrong type for Underlying method)
		have Underlying() "go/types".Type
		want Underlying() "golang.org/x/tools/go/types".Type
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:347: cannot use ty (type "go/types".Type) as type "golang.org/x/tools/go/types".Type in argument to c.p.anonTypeMap.Set:
	"go/types".Type does not implement "golang.org/x/tools/go/types".Type (wrong type for Underlying method)
		have Underlying() "go/types".Type
		want Underlying() "golang.org/x/tools/go/types".Type
```

**Comment by shurcooL** [comment]
You need to use Go 1.6. GopherJS only works with 1.6 and not older versions.

What does `go version` print?

If it's 1.6, then you should be able to do `go get -u github.com/gopherjs/gopherjs` and have it work. Can you try it again? I've just tested, and it should work.

**Comment by almansi** [comment]
Hello Dimitri,

yes, I'm using 1.6:
go version go1.6 linux/amd64

**Comment by shurcooL** [comment]
Can you try running `go get -u github.com/gopherjs/gopherjs` again and print all of the output it gives you?

It looks like your `golang.org/x/tools/go/types/typeutil` package is out of date. But the `-u` flag should cause it to get updated.

**Comment by almansi** [comment]
It worked now!

I first removed the existing go/src/github.com/gopherjs folder, run again
 go get -u github.com/gopherjs/gopherjs, and it worked. Thanks a lot.

On Sat, Mar 26, 2016 at 10:03 PM, Dmitri Shuralyov <notifications@github.com

**Comment by almansi** [comment]
No, still does not work. I removed again the gopherjs folder, run the
command and I get the same error I got yesterday:

gopherjs/gopherjs/compiler/utils.go:341: cannot use ty (type
"go/types".Type) as type "golang.org/x/tools/go/types".Type in argument to
c.p.anonTypeMap.At:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type
gopherjs/gopherjs/compiler/utils.go:347: cannot use ty (type
"go/types".Type) as type "golang.org/x/tools/go/types".Type in argument to
c.p.anonTypeMap.Set:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type

**Comment by shurcooL** [comment]
So first it worked, then a second time it didn't work? That's really strange.

I can't reproduce the issue.

Can you try doing `go get -u golang.org/x/tools/go/types/typeutil`, does that work?

Maybe try deleting your `$GOPATH/pkg` cache.

**Comment by almansi** [comment]
I deleted gopherjs both from $GOPATH/pkg and $GOPATH/src and got typeutil,
but it seems that the problem with types remains:
:~$ go get -u golang.org/x/tools/go/types/typeutil
~$ go get -u github.com/gopherjs/gopherjs
# github.com/gopherjs/gopherjs/compiler
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:341: cannot use ty
(type "go/types".Type) as type "golang.org/x/tools/go/types".Type in
argument to c.p.anonTypeMap.At:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:347: cannot use ty
(type "go/types".Type) as type "golang.org/x/tools/go/types".Type in
argument to c.p.anonTypeMap.Set:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type

**Comment by shurcooL** [comment]
Did you also delete `golang.org/x/tools/go/types` from `$GOPATH/pkg` cache?

**Comment by almansi** [comment]
I did, but it shows up again as soon as I do
go get -u github.com/gopherjs/gopherjs

and go get still results in the same problem with types:
:~$ go get -u github.com/gopherjs/gopherjs
# github.com/gopherjs/gopherjs/compiler
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:341: cannot use ty
(type "go/types".Type) as type "golang.org/x/tools/go/types".Type in
argument to c.p.anonTypeMap.At:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type
Go/src/github.com/gopherjs/gopherjs/compiler/utils.go:347: cannot use ty
(type "go/types".Type) as type "golang.org/x/tools/go/types".Type in
argument to c.p.anonTypeMap.Set:
"go/types".Type does not implement "golang.org/x/tools/go/types".Type
(wrong type for Underlying method)
have Underlying() "go/types".Type
want Underlying() "golang.org/x/tools/go/types".Type

**Comment by shurcooL** [comment]
I see. I'm really stumped. I'm pretty confident there's something broken about your Go installation, but I'm not sure what it is.

Do you have another computer or a temporary virtual machine to try this on?

I've [done that just now](https://cloud.githubusercontent.com/assets/1924134/14072007/2d228a52-f470-11e5-8382-a0f0bedb9d2b.png), and again, it worked without issues for me, as expected.

Alternatively, can you try the following. Get a tool named `gostatus`, and then run it on all packages relevant to GopherJS. Basically, run these 2 command and paste the exact output you get:

```bash
go get -u github.com/shurcooL/gostatus
go list -f '{{join .Deps "\n"}}' github.com/gopherjs/gopherjs | gostatus -stdin -v
```

Also, what does `go env` print?

**Comment by almansi** [comment]
1.this is what I get from gostatus:
     github.com/spf13/cobra/...
     github.com/spf13/pflag/...
     github.com/kardianos/osext/...
     github.com/fsnotify/fsnotify/...
     github.com/neelance/sourcemap/...
  +  github.com/gopherjs/gopherjs/...
     golang.org/x/crypto/...
  #  golang.org/x/tools/...

2. go env gives the following:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/myhome/Go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

**Comment by shurcooL** [comment]
Ah, that gives me a clue as to what's wrong!

Can you run `gostatus` once more with the following flags:

```bash
gostatus -v -debug github.com/gopherjs/gopherjs/... golang.org/x/tools/...
```

I suspect your golang.org/x/tools repo might be checked out from the wrong remote URL. The `#` means "Remote path doesn't match import path". That should be fixed. You'll need to remove the `golang.org/x/tools` folder from your `$GOPATH/src` completely and `go get` it again. Its remote should be `https://go.googlesource.com/tools` and not something else.

**Comment by almansi** [comment]
here we go:

:~$ gostatus -v -debug github.com/gopherjs/gopherjs/
{
"Path": "/home/achille/Go/src/github.com/gopherjs/gopherjs",
"Root": "github.com/gopherjs/gopherjs",
"DefaultBranch": "master",
"Local": {
"RemoteURL": "https://github.com/gopherjs/gopherjs",
"Status": "",
"Branch": "master",
"Revision": "14ba2f52062a79512bbb6768908c95032395ce94",
"Stash": ""
},
"Remote": {
"RepoURL": "https://github.com/gopherjs/gopherjs",
"Revision": "64858154c27789453689ac91041a736c89abd49d"
},
"LocalContainsRemoteRevision": false
}

and

gostatus -v -debug golang.org/x/tools/
{
	"Path": "/home/achille/Go/src/golang.org/x/tools",
	"Root": "golang.org/x/tools",
	"DefaultBranch": "default",
	"Local": {
		"RemoteURL": "https://code.google.com/p/go.tools",
		"Status": "",
		"Branch": "default",
		"Revision": "a7e14835e46bb13da10fa8b9c9c5e7f2f378f568",
		"Stash": ""
	},
	"Remote": {
		"RepoURL": "https://go.googlesource.com/tools",
		"Revision": "a7e14835e46bb13da10fa8b9c9c5e7f2f378f568"
	},
	"LocalContainsRemoteRevision": true
}

**Comment by shurcooL** [comment]
Yep, as I expected, that's the problem. Notice how your golang.org/x/tools is checked out from:

```
"Local": {
	"RemoteURL": "https://code.google.com/p/go.tools",
```

But it should be coming from "https://go.googlesource.com/tools".

Delete the entire `golang.org/x/tools` repo (the `/home/achille/Go/src/golang.org/x/tools` directory) and `go get` it again.

**Comment by almansi** [comment]
Perfect! It worked this time, and ~:$gopherjs build test1.go did what was
expected to do: it created test1.js and test1.js.map

Thanks a lot.

**Comment by shurcooL** [comment]
Great to hear!

I'll close this since your issue is resolved. If you have more question about GopherJS in the future, I recommend Slack channel, which you can see under [community section](https://github.com/gopherjs/gopherjs#community) in README.

If you discover bugs or problems with GopherJS, then please report it here.
